### ISSUE TITLE
不支持三级标题吗？

### ISSUE THREAD

**Issue by Veteran-ChengQin** [xiaobai-171/overleaf-latex-chinese-general-template#1]
当我使用subsubsection的时候发现报错了

**Comment by alan-tsang** [comment]
模板中定义了三级标题样式：\titleformat*{\subsubsection}{\raggedright\small\sectioncf}，且实际可用
![image](https://github.com/user-attachments/assets/82c464b3-58fb-46bf-abf5-abe1f9d86c42)。请首先确定有无误删除三级标题定义，并提供报错信息

**Comment by Veteran-ChengQin** [comment]
感谢你的回复，确实没问题的，我是因为语句中出现了`#`导致的，需要使用`\#`
