### ISSUE TITLE
如何使得左栏先占满再去占右栏？

### ISSUE THREAD

**Issue by czxvan** [xiaobai-171/overleaf-latex-chinese-general-template#2]
![image](https://github.com/user-attachments/assets/01e222c3-bd87-4d86-888e-eaad7fba6696)
如图，现在会倾向保持两边高度一致，请问如何使得左边先占满再去占右边？

**Comment by czxvan** [comment]
![ac8de79d200dfcef8c857698bbb352d](https://github.com/user-attachments/assets/4b3c7ebf-7833-4dae-995f-1385c4fcba68)
Got it.

**Comment by alan-tsang** [comment]
yeah, you can change to multicols{2}
