### ISSUE TITLE
pdflatex无法编译

### ISSUE THREAD

**Issue by JoseBrylin** [xiaobai-171/overleaf-latex-chinese-general-template#3]
使用环境: 编译器LaTex Live2024，编辑器TeXstudio 4.8.1，Win10系统
您好，我使用Latex的环境如上。但是无法使用pdflatex编译，xelatex方式可以正常使用。请问您是否考虑将文档默认编译方式改为xelatex，即在文档开始添加‘%!TEX program = xeflatex’。 xeflatex编译方式能更好的兼容中文排版。

**Comment by alan-tsang** [comment]
感谢补充。大多数编译器默认选项是pdflatex，模板不支持的情况下，显式设置xelatex为默认值是有必要的 #4

**Comment by JoseBrylin** [comment]
> 感谢补充。大多数编译器默认选项是pdflatex，模板不支持的情况下，显式设置xelatex为默认值是有必要的 #4

好的，问题已经解决。我现在将issue关掉。
